apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../ffc-sfd-customer-receiver-preferences
- ../../ffc-sfd-customer-receiver-payments
- ../../ffc-sfd-ingress
- ../../ffc-sfd-crm
- ../../ffc-sfd-messages-processor
- ../../ffc-sfd-data
- ../../ffc-sfd-permissions-api
- ../../ffc-sfd-customer-receiver-messages
- ../../ffc-sfd-customer-receiver-queries
- ../../ffc-sfd-queries
- ../../ffc-sfd-ahwp-stub
