apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ffc-demo-payment-service
  namespace: flux-config
spec:
  chart:
    spec:
      version: 4.2.24 # {"$imagepolicy": "flux-config:ffc-demo-payment-service-snd-02:tag"}
  values:
    environment: production
    name: ffc-demo-payment-service
    namespace: fcp-demo
    image: sndadpinfcr2401.azurecr.io/image/ffc-demo-payment-service:4.2.24 # {"$imagepolicy": "flux-config:ffc-demo-payment-service-snd-02"}
    serviceAccount:
      name: ffc-demo-payment-service
    container:
      imagePullPolicy: Always
    deployment:
      priorityClassName: default
    containerConfigMap:
      configServiceName: ${APPCONFIG_NAME}
      configServiceMIClientId: ${APPCONFIG_MI_CLIENTID}
      serviceMIClientId: ${clientId}
