apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

# patches:
#   - path: workload-identity.yaml
#   - path: kustomize.yaml
#     target:
#       kind: Kustomization
