apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../adp-test-dr111
- ../../adp-test-drcsggwg
- ../../adp-demo-11
- ../../adp-demo-eee
- ../../ccts-adp-permissions-test-1
- ../../ccts-adp-test-frontend3
