apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ffc-demo-payment-service
  namespace: flux-config
spec:
  chart:
    spec:
      version: "0.1.0" # {"$imagepolicy": "flux-config:ffc-demo-payment-service-snd-02:tag"}
  values:
    environment: production
    name: ffc-demo-payment-service
    namespace: ffc-demo
    image: sndadpinfcr2401.azurecr.io/image/ffc-demo-payment-service:0.1.0 # {"$imagepolicy": "flux-config:ffc-demo-payment-service-snd-02"}
    serviceAccount:
      name: ffc-demo-payment-service
    deployment:
      priorityClassName: default
    container:
      imagePullPolicy: Always
      requestMemory: 5Mi
      requestCpu: 5m
      limitMemory: 60Mi
      limitCpu: 40m
    containerConfigMap:
      configServiceName: ${APPCONFIG_NAME}
      configServiceMIClientId: ${APPCONFIG_MI_CLIENTID}
      serviceMIClientId: ${clientId}
