apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - aso-helm-repository.yaml
  # - aso-helm-release.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - image-repository.yaml  
  - image-policy.yaml
