apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ffc-demo-payment-service
  namespace: flux-config
spec:
  chart:
    spec:
      version: "4.2.21" # {"$imagepolicy": "flux-config:ffc-demo-payment-service-snd-01:tag"}
  values:
    environment: production
    name: ffc-demo-payment-service
    namespace: ffc-demo
    image: sndadpinfcr1401.azurecr.io/image/ffc-demo-payment-service:4.2.21 # {"$imagepolicy": "flux-config:ffc-demo-payment-service-snd-01"}
    serviceAccount:
      name: ffc-demo-payment-service
    deployment:
      priorityClassName: default
    container:
      imagePullPolicy: Always
    containerConfigMap:
      configServiceName: ${APPCONFIG_NAME}
      configServiceMIClientId: ${APPCONFIG_MI_CLIENTID}
      serviceMIClientId: ${clientId}
