apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- image-update.yaml
- notification.yaml
- ../../../adp-platform/kustomize.yaml
- ../../../ccts/ccts-adp/base/patch
- ../../../crai/crai-mcu/base/patch
- ../../../fcp/fcp-ea-walleys-quarry/base/patch
- ../../../ncea/ncea-search/base/patch
- ../../../eutd/eutd-trade-exports-core/base/patch
- ../../../fcp/fcp-sfd/base/patch
- ../../../fcp/fcp-demo/base/patch
- ../../../ccts/ccts-adp-test/base/patch
