apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-base
resources:
  - kustomize.yaml
  - ../base

# patches:
#   - path: kustomize.yaml
#     target:
#       kind: Kustomization