apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../ffc-demo-web
- ../../ffc-demo-payment-web
- ../../ffc-demo-claim-service
- ../../ffc-demo-payment-service
