apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ccts-adp-permissions-test-1
  namespace: flux-config
spec:
  chart:
    spec:
      version: 0.1.0 # {"$imagepolicy": "flux-config:ccts-adp-permissions-test-1-snd-04:tag"}
  values:
    environment: production
    name: ccts-adp-permissions-test-1
    namespace: ccts-adp
    teamResourceGroupName: ${TEAM_RG}
    image: sndadpinfcr4401.azurecr.io/image/ccts-adp-permissions-test-1:0.1.0 # {"$imagepolicy": "flux-config:ccts-adp-permissions-test-1-snd-04"}
    serviceAccount:
      name: ccts-adp-permissions-test-1
    container:
      imagePullPolicy: Always
    deployment:
      priorityClassName: default
    containerConfigMap:
      configServiceName: ${APPCONFIG_NAME}
      configServiceMIClientId: ${APPCONFIG_MI_CLIENTID}
      serviceMIClientId: ${clientId}
    storageAccountPrefix: ${STORAGEACCOUNT_PREFIX}
    enablePrivateEndpoint: ${ENABLE_PRIVATE_ENDPOINT}
