apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- image-update.yaml
- notification.yaml
- ../../../ffc/ffc-demo/base/patch
- ../../../adp-platform/kustomize.yaml
- ../../../eutd/eutd-find-my-pet/base/patch
- ../../../eutd/eutd-find-my-cat/base/patch
- ../../../ccts/ccts-adp/base/patch
- ../../../crai/crai-mcu/base/patch
- ../../../ffc/fcp-dal/base/patch
- ../../../ncea/ncea-search/base/patch
- ../../../eutd/eutd-trade-exports-core/base/patch
- ../../../fcp/fcp-sfd/base/patch
- ../../../eutd/eutd-test/base/patch
