apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- image-update.yaml
- notification.yaml
- ../../../ffc/ffc-demo/base/patch
- ../../../ffc/ffc-ffd/base/patch
- ../../../ffc/ffc-dal/base/patch
- ../../../adp-platform/kustomize.yaml
- ../../../eutd/eutd-trade-exports-ai/base/patch
- ../../../ffc/ffc-find/base/patch
- ../../../ffc/ffc-sfd/base/patch
- ../../../lap/lap-mit/base/patch
- ../../../ffc/fcp-find/base/patch
- ../../../ncea/ncea-search/base/patch
- ../../../eutd/eutd-find-my-pet/base/patch
- ../../../eutd/eutd-find-my-cat/base/patch
- ../../../ccts/ccts-adp/base/patch
- ../../../crai/crai-mcu/base/patch
- ../../../ffc/fcp-dal/base/patch
- ../../../fcp/fcp-ea-walleys-quarry/base/patch
- ../../../fcp/fcp-demo/base/patch
- ../../../eutd/eutd-trade-exports-core/base/patch
- ../../../fcp/fcp-sfd/base/patch
- ../../../test-prog1/tpe-findmydog/base/patch
