apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - image-update.yaml
  - ../../../ffc-demo/base/patch
  - ../../../ffc-ffd/base/patch
  - ../../../ffc/ffc-demo/base/patch
  - ../../../ffc/ffc-ffd/base/patch
