apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- image-update.yaml
- notification.yaml
- ../../../ffc/ffc-ffd/base/patch
- ../../../adp-platform/kustomize.yaml
- ../../../eutd/eutd-trade-exports-ai/base/patch
- ../../../ffc/ffc-find/base/patch
- ../../../ffc/fcp-find/base/patch
- ../../../ncea/ncea-search/base/patch
- ../../../ccts/ccts-adp/base/patch
- ../../../crai/crai-mcu/base/patch
- ../../../fcp/fcp-ea-walleys-quarry/base/patch
- ../../../eutd/eutd-trade-exports-core/base/patch
- ../../../ccts/ccts-adp-test/base/patch
- ../../../ccts-test/ttt-adp-test/base/patch
